# Site settings
title: Jenna M. Hershberger
email: jmh579@cornell.edu
description: <b>USDA NIFA AFRI EWD Predoctoral Fellow</b><b>PhD candidate</b> at Cornell University<br>Graduating <b>Spring 2021</b>
baseurl: "" # the subpath of your site, e.g. /blog
url: "jmh579.github.io" # the base hostname & protocol for your site
author: Jenna M. Hershberger
street_address: 353 Plant Science Building
city: Ithaca
state: NY
zip_code: 14850
country: United States of America
phone: (555) 555-5555

icon: fa-seedling # Font Awesome class for your site's icon

# Social settings
facebook_url:
github_url: https://github.com/jmh579
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/jenna-hershberger
pinterest_url:
slack_url:
twitter_url: https://twitter.com/jennahersh
#  googlescholar: https://scholar.google.com/citations?user=

# Build settings
markdown: kramdown

sass:
style: compressed
