# Site settings
title: Jenna M. Hershberger
email: jmh579@cornell.edu
description:     <b>PhD candidate</b> at Cornell University
    Graduating <b>Spring 2021</b>
baseurl: "" # the subpath of your site, e.g. /blog
url: "jmh579.github.io" # the base hostname & protocol for your site
author: Jenna M. Hershberger
#street_address: 1234 Somewhere Road
#city: Nashville
#state: TN
#zip_code: 55555
#country: United States of America
#phone: (716) 555-5555

icon: fa-seedling # Font Awesome class for your site's icon

# Social settings
facebook_url:
github_url: https://github.com/jmh579
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/jenna-hershberger
pinterest_url:
slack_url:
twitter_url: https://twitter.com/jennahersh
#  googlescholar: https://scholar.google.com/citations?user=NMlhaEsAAAAJ&hl=en

# Build settings
markdown: kramdown

sass:
style: compressed